version: '3.8'

services:
  db:
    image: mysql:5.7
    container_name: docker_mysql
    restart: always
    volumes:
      - db-data:/var/lib/mysql
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: 'yes'
    networks:
      - dev

  phpmyadmin:
    depends_on:
      - db
    image: phpmyadmin/phpmyadmin:latest
    container_name: docker_phpmyadmin
    restart: always
    environment:
      PMA_HOST: db
    ports:
      - "8080:80"
    networks:
      - dev

  www:
    build: ./php
    container_name: docker_www
    ports:
      - "8082:80"
    volumes:
      - ./php/vhosts:/etc/apache2/sites-enabled
      - ./:/var/www/html
    restart: always
    networks:
      - dev

networks:
  dev:

volumes:
  db-data:
